services:
  database:
    image: postgres:14.4-alpine3.16
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "yellowtaxi"
      POSTGRES_USER: "yellowtaxiUser"
      POSTGRES_PASSWORD: "pass1"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/create_tables.sql